const menu = [
  {
    id: 1,
    title: 'Panquecas Cartoon',
    category: 'Café da manhã',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `Panqueca feita com todos os ingredientes necessários para permitir deliciar uma verdadeira panqueca de desenho animado `,
  },
  {
    id: 2,
    title: 'double trouble',
    category: 'Lanches',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `Nada mais básico do que um Duplo Probleminha que você precise enfrentar sozinho, não acha? `,
  },
  {
    id: 3,
    title: 'milkshake Delicia',
    category: 'shakes',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `Delicioso shake feito para você é, ou se considera uma delícia.`,
  },
  {
    id: 4,
    title: 'Café dos Campeões',
    category: 'Café da manhã',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `O classico café dos campeões mas campeão mesmo é o sentimento de poder comer esse prato`,
  },
  {
    id: 5,
    title: 'Olhudão',
    category: 'Lanches',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `Um poderoso hamburguer que é completamente coberto por uma capa de ovo frito, o clássico Olhudão `,
  },
  {
    id: 6,
    title: 'oreo bomb',
    category: 'shakes',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `Cup de milkshake misturado a pedaços de oreo misturado a calda de chocolate`,
  },
  {
    id: 7,
    title: 'bacon Zin',
    category: 'Café da manhã',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `pãozinho levezinho com recheiozinho de queijinho, ovinho e claro baconzinho. `,
  },
  {
    id: 8,
    title: 'classico americano',
    category: 'Lanches',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `O ambicioso hamburger americano acompanhado de batata frita, todos cheio de oil  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `Aquele gigantesco shake feito para dividir com quem está do seu lado sempre respeitando os padrões de segurança OMS.`,
  },
];
export default menu;
